using System.Text;

namespace GodotTrellis.Generator;

internal static class Emitter
{
    public static string Emit(ClassModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by GodotTrellis.Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using GodotTrellis;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{model.Accessibility} partial class {model.ClassName}");
        sb.AppendLine("{");

        // Resolver field and property
        sb.AppendLine("    private GodotTrellis.DependencyResolver? __deps;");
        sb.AppendLine("    internal GodotTrellis.DependencyResolver __Deps");
        sb.AppendLine("        => __deps ??= new GodotTrellis.DependencyResolver(this);");
        sb.AppendLine();

        for (var i = 0; i < model.Properties.Count; i++)
        {
            var prop = model.Properties[i];

            if (prop.IsCollection)
                EmitCollectionProperty(sb, prop);
            else if (prop.IsOptional)
                EmitOptionalProperty(sb, prop);
            else
                EmitRequiredProperty(sb, prop);

            if (i < model.Properties.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitRequiredProperty(StringBuilder sb, PropertyModel prop)
    {
        var resolveType = prop.TypeName;
        var args = BuildArgs(prop);

        sb.AppendLine($"    {prop.AccessModifier} partial {prop.TypeName} {prop.PropertyName}");
        sb.AppendLine($"        => __Deps.Resolve<{resolveType}>({args});");
    }

    private static void EmitOptionalProperty(StringBuilder sb, PropertyModel prop)
    {
        // The type already includes '?' from the user's declaration.
        // ResolveOptional returns T? so we need the non-nullable type for the generic arg.
        var resolveType = prop.TypeName.TrimEnd('?');
        var args = BuildArgs(prop);

        sb.AppendLine($"    {prop.AccessModifier} partial {prop.TypeName} {prop.PropertyName}");
        sb.AppendLine($"        => __Deps.ResolveOptional<{resolveType}>({args});");
    }

    private static void EmitCollectionProperty(StringBuilder sb, PropertyModel prop)
    {
        var elementType = prop.CollectionElementTypeName!;
        var args = BuildArgs(prop);

        sb.AppendLine($"    {prop.AccessModifier} partial {prop.TypeName} {prop.PropertyName}");
        sb.AppendLine($"        => __Deps.ResolveAll<{elementType}>({args});");
    }

    private static string BuildArgs(PropertyModel prop)
    {
        var parts = new List<string>();

        parts.Add($"GodotTrellis.ResolveStrategy.{prop.Strategy}");

        if (prop.GroupName is not null)
            parts.Add($"groupName: \"{EscapeString(prop.GroupName)}\"");

        if (prop.Deep)
            parts.Add("deep: true");

        if (prop.UseSceneFilePath)
            parts.Add("useSceneFilePath: true");

        return string.Join(", ", parts);
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}