using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace GodotTrellis.Generator;

internal static class Emitter
{
    public static string Emit(ClassModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by GodotTrellis.Generator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using GodotTrellis;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"{model.Accessibility} partial class {EscapeIdentifier(model.ClassName)}");
        sb.AppendLine("{");

        // Resolver field and property
        sb.AppendLine("    private GodotTrellis.DependencyResolver? __trellis;");
        sb.AppendLine("    internal GodotTrellis.DependencyResolver GDTrellis");
        sb.AppendLine("        => __trellis ??= new GodotTrellis.DependencyResolver(this);");
        sb.AppendLine();

        for (var i = 0; i < model.Properties.Count; i++)
        {
            var prop = model.Properties[i];

            if (prop.IsCollection)
                EmitCollectionProperty(sb, prop);
            else if (prop.IsOptional)
                EmitOptionalProperty(sb, prop);
            else
                EmitRequiredProperty(sb, prop);

            if (i < model.Properties.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitRequiredProperty(StringBuilder sb, PropertyModel prop)
    {
        var resolveType = prop.TypeName;
        var args = BuildArgs(prop);
        var propertyName = EscapeIdentifier(prop.PropertyName);

        sb.AppendLine($"    {prop.AccessModifier} partial {prop.TypeName} {propertyName}");
        sb.AppendLine($"        => GDTrellis.Resolve<{resolveType}>({args});");
    }

    private static void EmitOptionalProperty(StringBuilder sb, PropertyModel prop)
    {
        var resolveType = prop.OptionalResolveTypeName ?? prop.TypeName;
        var args = BuildArgs(prop);
        var propertyName = EscapeIdentifier(prop.PropertyName);

        sb.AppendLine($"    {prop.AccessModifier} partial {prop.TypeName} {propertyName}");
        sb.AppendLine($"        => GDTrellis.ResolveOptional<{resolveType}>({args});");
    }

    private static void EmitCollectionProperty(StringBuilder sb, PropertyModel prop)
    {
        var elementType = prop.CollectionElementTypeName!;
        var args = BuildArgs(prop);
        var propertyName = EscapeIdentifier(prop.PropertyName);

        sb.AppendLine($"    {prop.AccessModifier} partial {prop.TypeName} {propertyName}");
        sb.AppendLine($"        => GDTrellis.ResolveAll<{elementType}>({args});");
    }

    private static string BuildArgs(PropertyModel prop)
    {
        var parts = new List<string>();

        parts.Add($"GodotTrellis.ResolveStrategy.{prop.Strategy}");

        if (prop.GroupName is not null)
            parts.Add($"groupName: {ToStringLiteral(prop.GroupName)}");

        if (prop.Deep)
            parts.Add("deep: true");

        if (prop.UseSceneFilePath)
            parts.Add("useSceneFilePath: true");

        return string.Join(", ", parts);
    }

    private static string EscapeIdentifier(string identifier)
    {
        if (identifier.StartsWith("@", StringComparison.Ordinal))
            return identifier;

        if (SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
            SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None)
        {
            return $"@{identifier}";
        }

        return identifier;
    }

    private static string ToStringLiteral(string value)
    {
        return SyntaxFactory.LiteralExpression(
            SyntaxKind.StringLiteralExpression,
            SyntaxFactory.Literal(value))
            .ToFullString();
    }
}